# Generated by Django 5.2.1 on 2025-06-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('related_products', models.TextField(help_text='List or description of related products')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ritual_images/')),
            ],
        ),
    ]
