# Generated by Django 5.2 on 2025-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rituals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ritual',
            name='magic_properties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
