# Generated by Django 5.2.1 on 2025-06-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_spell', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayspell',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
