# Generated by Django 5.2.1 on 2025-06-09 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day_spell', '0002_alter_dayspell_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dayspell',
            table='dayspell',
        ),
    ]
